name: Build and Push Docker Image to Docker Hub on Master

# Trigger the workflow on push events to the 'master' branch
on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering from the Actions tab

env:
  # !!! IMPORTANT: SET THESE !!!
  # Your Docker Hub username
  DOCKERHUB_USERNAME: filippoalbertini
  # The name you want for your image on Docker Hub (e.g., my-aspnet-app)
  IMAGE_NAME: DeployToAWS

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container  # Specify the docker-container driver
          buildkitd-flags: --debug

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --file ./Dockerfile \
            --push \
            --tag filippoalbertini/deploytoaws:latest
